import "dotenv/config";
import { eq } from "drizzle-orm";
import { v4 as uuidv4 } from "uuid";
import { db } from "../src/db";
import {
	businessUnit,
	department,
	employee,
	jobTitle,
	legalEntity,
	location,
} from "../src/db/schema";
import { user } from "../src/db/schema/auth";

// Employee data - parsed from the provided list
const employeeData = [
	{
		email: "",
		dateOfJoining: "2005-06-01",
		jobTitle: "HOD",
		businessUnit: "Gold Showroom",
		department: "Long Necklace",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "vigneshsravanthi9966@gmail.com",
		dateOfJoining: "2003-04-15",
		jobTitle: "Purchase Manager",
		businessUnit: "Corp Office",
		department: "Gold",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "MURALI.K.M",
	},
	{
		email: "vishnuvaradhan.@gmail.com",
		dateOfJoining: "2013-01-10",
		jobTitle: "Mentor",
		businessUnit: "Gold Showroom",
		department: "Diamond",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "ramalingamsvtm@gmail.com",
		dateOfJoining: "1992-09-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Thali",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "anant@vasavi.com",
		dateOfJoining: "1999-07-07",
		jobTitle: "HOD",
		businessUnit: "Gold Showroom",
		department: "Chain",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "hariharish2607@gmail.com",
		dateOfJoining: "2004-11-26",
		jobTitle: "Mentor",
		businessUnit: "Gold Showroom",
		department: "Bangle",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "srikarthikj01@gmail.com",
		dateOfJoining: "1997-06-01",
		jobTitle: "Cashier",
		businessUnit: "Gold Showroom",
		department: "Cash",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "emahendran1975@gmail.com",
		dateOfJoining: "2009-10-05",
		jobTitle: "CRO",
		businessUnit: "Gold Showroom",
		department: "Appraiser",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "sekar@vasavi.com",
		dateOfJoining: "2008-03-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Short Necklace",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "j.karthik1206@gmail.com",
		dateOfJoining: "2003-05-01",
		jobTitle: "Cashier",
		businessUnit: "Gold Showroom",
		department: "Cash",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "saravanakumarsvtm@gmail.com",
		dateOfJoining: "1997-07-03",
		jobTitle: "Cashier",
		businessUnit: "Gold Showroom",
		department: "Cash",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "kumaranbk37@gmail.com",
		dateOfJoining: "2012-04-01",
		jobTitle: "Executive",
		businessUnit: "Corp Office",
		department: "Gold Barcode",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "MURALI.K.M",
	},
	{
		email: "sak@vasavi.com",
		dateOfJoining: "2014-12-20",
		jobTitle: "Sales Executive",
		businessUnit: "Silver Showroom",
		department: "One gram",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "sivavignesh624@gmail.com",
		dateOfJoining: "2014-05-01",
		jobTitle: "Section head",
		businessUnit: "Gold Showroom",
		department: "Short Necklace",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "sarav@vasavisubburamani.com",
		dateOfJoining: "2018-04-01",
		jobTitle: "Sales Executive",
		businessUnit: "Silver Showroom",
		department: "Golusu",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "",
		dateOfJoining: "1996-05-02",
		jobTitle: "HOD",
		businessUnit: "Gold Showroom",
		department: "Stud",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "janak@vasavi.com",
		dateOfJoining: "2003-06-11",
		jobTitle: "Executive",
		businessUnit: "Gold Showroom",
		department: "Store",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "PREMKUMAR",
	},
	{
		email: "bm674407@gmail.com",
		dateOfJoining: "2013-03-08",
		jobTitle: "Sales Executive",
		businessUnit: "Corp Office",
		department: "Stud",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "siva77785@gmail.com",
		dateOfJoining: "1998-07-12",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Ring",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "sheelarosemary700@gmail.com",
		dateOfJoining: "2016-02-02",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Stud",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "nirmala32@svtmjewels.com",
		dateOfJoining: "2025-08-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Boutique",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "kv23180@gmail.com",
		dateOfJoining: "2009-05-04",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Sales Executive",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "srini@vasavi.com",
		dateOfJoining: "2017-05-02",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "suresh2561966@gmail.com",
		dateOfJoining: "1997-12-01",
		jobTitle: "Purchase Manager",
		businessUnit: "Corp Office",
		department: "Silver",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "MURALI.K.M",
	},
	{
		email: "sivakumar16371@gmail.com",
		dateOfJoining: "2000-08-06",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Diamond",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "maheshwari562003@gmail.com",
		dateOfJoining: "2022-09-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Stud",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "sureshrenugadevi20@gmail.com",
		dateOfJoining: "1996-12-01",
		jobTitle: "Floor Manager",
		businessUnit: "Silver Showroom",
		department: "Floor Manager",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "PREMKUMAR",
	},
	{
		email: "devikaa2001199@gmail.com",
		dateOfJoining: "2019-02-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Stud",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "rameshpadma.rp@gmail.com",
		dateOfJoining: "2017-08-03",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Chain",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "mariyappandgl464@gmail.com",
		dateOfJoining: "2003-06-01",
		jobTitle: "Sales Executive",
		businessUnit: "Silver Showroom",
		department: "Vessels",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "kalaivanikalaivani036@gmail.com",
		dateOfJoining: "2013-04-17",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Bangles",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "rpandian950@gmail.com",
		dateOfJoining: "2013-11-10",
		jobTitle: "Cashier",
		businessUnit: "Gold Showroom",
		department: "Cash",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "murali.km441@gmail.com",
		dateOfJoining: "2003-05-19",
		jobTitle: "Purchase Manager",
		businessUnit: "Corp Office",
		department: "Gold",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "PREMKUMAR",
	},
	{
		email: "sathishkumar491985@gmail.com",
		dateOfJoining: "2000-04-10",
		jobTitle: "Floor Manager",
		businessUnit: "Gold Showroom",
		department: "Floor Manager",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "PREMKUMAR",
	},
	{
		email: "venkatesan1972vtm@gmail.com",
		dateOfJoining: "1989-03-01",
		jobTitle: "CRO",
		businessUnit: "Gold Showroom",
		department: "Long Necklace",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "sangeethamookan@gmail.com",
		dateOfJoining: "2024-09-19",
		jobTitle: "Reception",
		businessUnit: "Silver Showroom",
		department: "Telecalling",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "KARTHICK",
	},
	{
		email: "dgm@svtmjewels.com",
		dateOfJoining: "2003-04-15",
		jobTitle: "Purchase Manager",
		businessUnit: "Gold Showroom",
		department: "Gold",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "",
	},
	{
		email: "ratha@vasavibalsam.com",
		dateOfJoining: "2018-06-18",
		jobTitle: "Sales Executive",
		businessUnit: "Silver Showroom",
		department: "Silver Ornaments",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "vaishnavy651@gmail.com",
		dateOfJoining: "2011-10-11",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Bangle",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "beenakittu83@gmail.com",
		dateOfJoining: "2007-06-01",
		jobTitle: "CRO",
		businessUnit: "Gold Showroom",
		department: "Appraiser",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "mohanrenuga55333@gmail.com",
		dateOfJoining: "2006-05-01",
		jobTitle: "Mentor",
		businessUnit: "Silver Showroom",
		department: "Golusu",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "radhikadgl1991@gmail.com",
		dateOfJoining: "2005-01-01",
		jobTitle: "Executive",
		businessUnit: "Corp Office",
		department: "Barcode - Silver",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "thangavelc421@gmail.com",
		dateOfJoining: "2009-12-01",
		jobTitle: "Mentor",
		businessUnit: "Silver Showroom",
		department: "Silver Ornaments",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "arunkumarkannan3112@gmail.com",
		dateOfJoining: "2012-04-09",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Diamond",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "srilakshmivenkatesh22@gmail.coo",
		dateOfJoining: "2014-06-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Chain",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "rsenthilbabu1984@gmail.com",
		dateOfJoining: "1999-04-03",
		jobTitle: "Floor Manager",
		businessUnit: "Gold Showroom",
		department: "Floor Manager",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "PREMKUMAR",
	},
	{
		email: "bhuvaneshkumara7@gmail.com",
		dateOfJoining: "2005-06-04",
		jobTitle: "Sales Executive",
		businessUnit: "Silver Showroom",
		department: "Vessels",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "",
		dateOfJoining: "2024-11-13",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Second Floor Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "jenib@vasavimalarkodi.com",
		dateOfJoining: "2010-07-10",
		jobTitle: "HOD",
		businessUnit: "Gold Showroom",
		department: "Boutique",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "sangeethagvnb@gmail.com",
		dateOfJoining: "2016-01-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Thali",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "ravim@vasavi.com",
		dateOfJoining: "2009-02-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Ring",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "balamurugan16051990@gmail.com",
		dateOfJoining: "2009-01-01",
		jobTitle: "Executive",
		businessUnit: "Corp Office",
		department: "Gold Barcode",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "MURALI.K.M",
	},
	{
		email: "vchinnachamy1976@gmail.com",
		dateOfJoining: "2021-02-10",
		jobTitle: "CRO",
		businessUnit: "Gold Showroom",
		department: "Appraiser",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "gopigb1109@gmail.com",
		dateOfJoining: "2012-01-12",
		jobTitle: "Cashier",
		businessUnit: "Gold Showroom",
		department: "Cash",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "ssudha1362@gmail.com",
		dateOfJoining: "2012-09-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Stud",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "vasan@vasavi.com",
		dateOfJoining: "2012-01-01",
		jobTitle: "Cashier",
		businessUnit: "Gold Showroom",
		department: "Cash",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "rooparajeshkanna@gmail.com",
		dateOfJoining: "2014-08-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Chain",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "sathish90437@gmail.com",
		dateOfJoining: "2024-11-13",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Kids",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "balasvtm@gmail.com",
		dateOfJoining: "2003-04-01",
		jobTitle: "Floor Manager",
		businessUnit: "Gold Showroom",
		department: "Floor Manager",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "PREMKUMAR",
	},
	{
		email: "saroja@vasavi.com",
		dateOfJoining: "2024-09-19",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Ground Floor Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "durga@vasavi.com",
		dateOfJoining: "2015-05-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Ring",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "yogeshkumaar762@gmail.com",
		dateOfJoining: "2024-09-19",
		jobTitle: "Accounts Executive",
		businessUnit: "Corp Office",
		department: "Accounts",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "EUGINE SAHAYARAJ.J",
	},
	{
		email: "hr@svtmjewels.com",
		dateOfJoining: "2023-07-31",
		jobTitle: "HR",
		businessUnit: "Gold Showroom",
		department: "HR",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "",
	},
	{
		email: "rasik@vasavi.com",
		dateOfJoining: "2024-08-26",
		jobTitle: "First Floor Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "smuthamil239@gmail.com",
		dateOfJoining: "2024-08-26",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "balakrishnanb558@gmail.com",
		dateOfJoining: "2024-01-24",
		jobTitle: "Admin",
		businessUnit: "Corp Office",
		department: "Receptionist",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "PREMKUMAR",
	},
	{
		email: "sivababu280880@gmail.com",
		dateOfJoining: "2016-10-25",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Chain",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "vij@vasavi.com",
		dateOfJoining: "2016-08-23",
		jobTitle: "Sales Executive",
		businessUnit: "Silver Showroom",
		department: "Golusu",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "r.ven@vasavi.com",
		dateOfJoining: "2013-06-01",
		jobTitle: "Sales Executive",
		businessUnit: "Silver Showroom",
		department: "METTI",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "selva9323@gmail.com",
		dateOfJoining: "2016-09-16",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Chain",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "mkaruppiah123@gmail.com",
		dateOfJoining: "2016-01-13",
		jobTitle: "Cashier",
		businessUnit: "Gold Showroom",
		department: "Chit",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "ssshanmusundari1852@gmail.com",
		dateOfJoining: "2016-09-15",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Diamond",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "pandisivak24@gmail.com",
		dateOfJoining: "2018-07-16",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Boutique",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "venka@vasavi.com",
		dateOfJoining: "2016-08-04",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Boutique",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "jothinishanth993@gmail.com",
		dateOfJoining: "2018-07-16",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Short Necklace",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "nvkchandrasekaran@gmail.com",
		dateOfJoining: "2024-12-02",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "anupriya@gmail.com",
		dateOfJoining: "2016-09-04",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Long Necklace",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "skal@vasavi.com",
		dateOfJoining: "2015-11-19",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Boutique",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "gokulganesh2006gk@gmail.com",
		dateOfJoining: "2024-01-08",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "jeyjeyaprakash555@gmail.com",
		dateOfJoining: "2024-01-05",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Long Necklace",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "sekars@vasavi.com",
		dateOfJoining: "2024-01-08",
		jobTitle: "Reception",
		businessUnit: "Silver Showroom",
		department: "Reception",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "k.cit@vasavi.com",
		dateOfJoining: "2024-01-08",
		jobTitle: "Sales Executive",
		businessUnit: "Silver Showroom",
		department: "One gram",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "brind@vasavi.com",
		dateOfJoining: "2023-07-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Kids",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "mahalakshmi@gmail.com",
		dateOfJoining: "2024-11-18",
		jobTitle: "Receptionist",
		businessUnit: "Silver Showroom",
		department: "Receptionist",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "divyadiya1425@gmail.com",
		dateOfJoining: "2024-11-18",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Ground Floor Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "",
		dateOfJoining: "2024-09-23",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Second Floor Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "n.vinayagan@gmail.com",
		dateOfJoining: "2019-01-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Chain",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "riyoaro16@gmail.com",
		dateOfJoining: "2025-09-01",
		jobTitle: "Executive",
		businessUnit: "Corp Office",
		department: "Gold Barcode",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "MURALI.K.M",
	},
	{
		email: "srdhanus2019@gmail.com",
		dateOfJoining: "2019-05-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Vessels",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "johnbasco1971psnact@gmail.com",
		dateOfJoining: "2016-07-01",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "sar@vasavi.com",
		dateOfJoining: "2014-01-01",
		jobTitle: "House Keeping",
		businessUnit: "Gold Showroom",
		department: "House Keeping",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "muthumari1122000@gmail.com",
		dateOfJoining: "2025-01-02",
		jobTitle: "Executive",
		businessUnit: "Silver Showroom",
		department: "Customer Care",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "KARTHICK",
	},
	{
		email: "arunachalam6700@gmail.com",
		dateOfJoining: "2009-08-14",
		jobTitle: "Executive",
		businessUnit: "Corp Office",
		department: "Hallmark",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "MURALI.K.M",
	},
	{
		email: "rockvel8056@gmail.com",
		dateOfJoining: "2024-08-26",
		jobTitle: "Silver Reception",
		businessUnit: "Silver Showroom",
		department: "Silver Reception",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "alame@vasavi.com",
		dateOfJoining: "2018-11-26",
		jobTitle: "House Keeping",
		businessUnit: "Gold Showroom",
		department: "House Keeping",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "krish@vasavi.com",
		dateOfJoining: "1991-01-08",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "maruthamuthu0282@gmail.com",
		dateOfJoining: "2017-06-17",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Stud",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "sinderani1984@gmail.com",
		dateOfJoining: "2024-09-23",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "kmaneeshwari@gmail.com",
		dateOfJoining: "2021-11-26",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Boutique",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "indhu@vasavi.com",
		dateOfJoining: "2023-11-27",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Vessels",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "m.mur@vasavi.com",
		dateOfJoining: "2006-06-26",
		jobTitle: "Reception",
		businessUnit: "Silver Showroom",
		department: "Reception",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "harigmh2209@gmail.com",
		dateOfJoining: "2019-04-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Diamond",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "mothi@vasavi.com",
		dateOfJoining: "2024-12-26",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "ganeshmechdgl@gmail.com",
		dateOfJoining: "2019-12-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Short Necklace",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "pandi@vasavil.com",
		dateOfJoining: "2018-03-01",
		jobTitle: "House Keeping",
		businessUnit: "Gold Showroom",
		department: "House Keeping",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "bala@vasavimurugan.com",
		dateOfJoining: "2011-06-01",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "karthickv1489@gmail.com",
		dateOfJoining: "2020-01-01",
		jobTitle: "CRM",
		businessUnit: "Silver Showroom",
		department: "CRM",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "PREMKUMAR",
	},
	{
		email: "manikandan01061991@gmail.com",
		dateOfJoining: "2024-02-14",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Boutique",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "prabamanikandan123@gmail.com",
		dateOfJoining: "2024-02-09",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "soundraya09101999@gmail.com",
		dateOfJoining: "2024-01-27",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "",
		dateOfJoining: "2025-01-01",
		jobTitle: "Executive",
		businessUnit: "Gold Showroom",
		department: "Diamond",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "gopi@svtmjewels.com",
		dateOfJoining: "2024-02-01",
		jobTitle: "SECURITY",
		businessUnit: "Silver Showroom",
		department: "SECURITY",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "daspihabanu@gmail.com",
		dateOfJoining: "2024-01-27",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Diamond",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "ugindgl@gmail.com",
		dateOfJoining: "2016-12-01",
		jobTitle: "Accounts Head",
		businessUnit: "Corp Office",
		department: "Accounts",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "PREMKUMAR",
	},
	{
		email: "inbam87@gmail.com",
		dateOfJoining: "2020-11-16",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Boutique",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "guhananu9@gmail.com",
		dateOfJoining: "2020-11-10",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Ring",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "sudha@vasavinataraja.com",
		dateOfJoining: "2023-08-18",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Silver Ornaments",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "sujitha.3196@gmail.com",
		dateOfJoining: "2024-08-26",
		jobTitle: "Accounts Executive",
		businessUnit: "Corp Office",
		department: "Accounts",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "EUGINE SAHAYARAJ.J",
	},
	{
		email: "punitharb1999@mail.com",
		dateOfJoining: "2020-12-15",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Boutique",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "nandhinivamsik@gmail.com",
		dateOfJoining: "2021-07-26",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Boutique",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "suthangiri9@gmail.com",
		dateOfJoining: "2020-02-14",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Chain",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "suryaprakash15092002@gmail.com",
		dateOfJoining: "2021-01-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Stud",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "subas@vasavisubburamani.com",
		dateOfJoining: "2025-07-04",
		jobTitle: "Sales Executive",
		businessUnit: "Silver Showroom",
		department: "Golusu",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "kamalakannan8925@gamil.com",
		dateOfJoining: "2021-06-01",
		jobTitle: "Executive",
		businessUnit: "Corp Office",
		department: "Gold Barcode",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "MURALI.K.M",
	},
	{
		email: "karthikeyan0327@gmail.com",
		dateOfJoining: "2021-06-06",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Stud",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "kamatchimathavan5@gmail.com",
		dateOfJoining: "2023-10-16",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "gayathrigayuammu875@gmail.com",
		dateOfJoining: "2021-07-26",
		jobTitle: "Executive",
		businessUnit: "Gold Showroom",
		department: "Cash",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "sakth@vasavisubraman.com",
		dateOfJoining: "1997-05-01",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "videoshop.svtmjewels@gmail.com",
		dateOfJoining: "2021-07-26",
		jobTitle: "Executive",
		businessUnit: "Gold Showroom",
		department: "Marketing",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "vijay@vasavi.com",
		dateOfJoining: "2020-06-08",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "sharvandgl88@gmail.com",
		dateOfJoining: "2021-08-02",
		jobTitle: "Floor Manager",
		businessUnit: "Gold Showroom",
		department: "Asst Manager",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "dhandayuthabani23@gmail.com",
		dateOfJoining: "2025-07-01",
		jobTitle: "Cashier",
		businessUnit: "Silver Showroom",
		department: "Cashier",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "vimal@vasavimunisam.com",
		dateOfJoining: "2016-03-01",
		jobTitle: "Helper",
		businessUnit: "Silver Showroom",
		department: "Kitchen",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "veera@vasavi.com",
		dateOfJoining: "2021-10-01",
		jobTitle: "House Keeping",
		businessUnit: "Silver Showroom",
		department: "House Keeping",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "b.kum@vasavi.com",
		dateOfJoining: "2005-06-01",
		jobTitle: "Aasari",
		businessUnit: "Silver Showroom",
		department: "Pattarai",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "kmuthumanivelkmuthumani@gmail.com",
		dateOfJoining: "2019-12-01",
		jobTitle: "Aasari",
		businessUnit: "Silver Showroom",
		department: "Pattarai",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "ksub@vasavi.com",
		dateOfJoining: "2005-06-30",
		jobTitle: "SECURITY",
		businessUnit: "Silver Showroom",
		department: "SECURITY",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "amuthabi28@gmail.com",
		dateOfJoining: "2013-11-07",
		jobTitle: "Executive",
		businessUnit: "Silver Showroom",
		department: "Data Entry",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "iiswarya215@gmail.com",
		dateOfJoining: "2021-08-31",
		jobTitle: "Executive",
		businessUnit: "Silver Showroom",
		department: "Data Entry",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "balam@vasavi.com",
		dateOfJoining: "2016-08-01",
		jobTitle: "Admin",
		businessUnit: "Gold Showroom",
		department: "Admin",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "PREMKUMAR",
	},
	{
		email: "ishak904675@gmail.com",
		dateOfJoining: "2016-08-01",
		jobTitle: "Executive",
		businessUnit: "Gold Showroom",
		department: "EDP",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "PREMKUMAR",
	},
	{
		email: "ganes@vasavi.com",
		dateOfJoining: "2004-03-01",
		jobTitle: "Aasari",
		businessUnit: "Gold Showroom",
		department: "Pattarai",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "nagar@vasavi.com",
		dateOfJoining: "2014-06-01",
		jobTitle: "Aasari",
		businessUnit: "Gold Showroom",
		department: "Pattarai",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "mohan@vasavi.com",
		dateOfJoining: "2019-03-01",
		jobTitle: "Aasari",
		businessUnit: "Gold Showroom",
		department: "Pattarai",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "parth@vasavi.com",
		dateOfJoining: "2016-01-01",
		jobTitle: "Driver",
		businessUnit: "Gold Showroom",
		department: "Driver",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "PREMKUMAR",
	},
	{
		email: "nehru@vasavi.com",
		dateOfJoining: "2019-01-22",
		jobTitle: "Driver",
		businessUnit: "Gold Showroom",
		department: "Driver",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "PREMKUMAR",
	},
	{
		email: "munis@vasavi.com",
		dateOfJoining: "2014-05-01",
		jobTitle: "SECURITY",
		businessUnit: "Gold Showroom",
		department: "SECURITY",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "tpal@vasavi.com",
		dateOfJoining: "2017-06-01",
		jobTitle: "SECURITY",
		businessUnit: "Gold Showroom",
		department: "SECURITY",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "satheesh081984@gmail.com",
		dateOfJoining: "2010-10-27",
		jobTitle: "Accounts Executive",
		businessUnit: "Gold Showroom",
		department: "Accounts",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "EUGINE SAHAYARAJ.J",
	},
	{
		email: "skl2782001@gmail.com",
		dateOfJoining: "2018-10-01",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "MURALI.K.M",
	},
	{
		email: "thanalakshmik24@gmail.com",
		dateOfJoining: "2021-01-01",
		jobTitle: "House Keeping",
		businessUnit: "Corp Office",
		department: "House Keeping",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "PREMKUMAR",
	},
	{
		email: "saravananithya90@gmail.com",
		dateOfJoining: "2024-03-18",
		jobTitle: "Executive",
		businessUnit: "Corp Office",
		department: "Gold Barcode",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "MURALI.K.M",
	},
	{
		email: "ksekar21267@gmail.com",
		dateOfJoining: "2014-04-05",
		jobTitle: "Executive",
		businessUnit: "Corp Office",
		department: "Purchase",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "MURALI.K.M",
	},
	{
		email: "mathiyalagan911@gmail.com",
		dateOfJoining: "2022-01-26",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Bangle",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "ramyag310803@gmail.com",
		dateOfJoining: "2022-01-27",
		jobTitle: "Executive",
		businessUnit: "Gold Showroom",
		department: "Ring",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "renugadass1044@gmail.com",
		dateOfJoining: "2024-11-05",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "murugavalli@vasavi.com",
		dateOfJoining: "2022-09-01",
		jobTitle: "House Keeping",
		businessUnit: "Gold Showroom",
		department: "House Keeping",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "mahal@vasaviselvam.com",
		dateOfJoining: "2022-08-03",
		jobTitle: "Helper",
		businessUnit: "Corp Office",
		department: "Kitchen",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "kanja@vasavi.com",
		dateOfJoining: "2022-04-01",
		jobTitle: "House Keeping",
		businessUnit: "Corp Office",
		department: "House Keeping",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "vidhyalakshmimurugesan@gmail.com",
		dateOfJoining: "2021-04-05",
		jobTitle: "Executive",
		businessUnit: "Corp Office",
		department: "Cashier",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "chith@vasavipillai.com",
		dateOfJoining: "2022-04-01",
		jobTitle: "Master",
		businessUnit: "Corp Office",
		department: "Kitchen",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "mahal@vasavisubbaiya.com",
		dateOfJoining: "2022-04-01",
		jobTitle: "Helper",
		businessUnit: "Corp Office",
		department: "Kitchen",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "mary2872001@gmail.com",
		dateOfJoining: "2024-08-26",
		jobTitle: "Executive",
		businessUnit: "Corp Office",
		department: "Customer Care",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "KARTHICK",
	},
	{
		email: "harsithaharsi2@gamil.com",
		dateOfJoining: "2022-08-01",
		jobTitle: "Executive",
		businessUnit: "Corp Office",
		department: "Golusu",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "laksh@vasavisanthara.com",
		dateOfJoining: "2022-10-01",
		jobTitle: "Sales Executive",
		businessUnit: "Corp Office",
		department: "Silver Ornaments",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "smanipriya15@gmail.com",
		dateOfJoining: "2022-10-01",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Kids",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "manodharshini276@gmail.com",
		dateOfJoining: "2023-08-21",
		jobTitle: "Executive",
		businessUnit: "Corp Office",
		department: "Customer Care",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "KARTHICK",
	},
	{
		email: "kugappriyakugappriya@gmail.com",
		dateOfJoining: "2022-11-11",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "sharmilokethaloketha@gmail.com",
		dateOfJoining: "2023-01-26",
		jobTitle: "Executive",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "senth@vasavisubburamanian.com",
		dateOfJoining: "2023-01-07",
		jobTitle: "Executive",
		businessUnit: "Silver Showroom",
		department: "Golusu",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "arunkamali961@gmail.com",
		dateOfJoining: "2024-05-07",
		jobTitle: "Sales Executive",
		businessUnit: "Silver Showroom",
		department: "Silver Ornaments",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "maniriya861@gmail.com",
		dateOfJoining: "2023-03-13",
		jobTitle: "Sales Executive",
		businessUnit: "Silver Showroom",
		department: "METTI",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "ml1911075@gmail.com",
		dateOfJoining: "2023-04-03",
		jobTitle: "Sales Executive",
		businessUnit: "Silver Showroom",
		department: "Golusu",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "suganyadevibalamurugan@gmail.com",
		dateOfJoining: "2023-05-08",
		jobTitle: "Executive",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "meenapandi1023@gmail.com",
		dateOfJoining: "2023-06-03",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "varshini430@gmail.com",
		dateOfJoining: "2023-06-12",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Diamond",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "kempsjraman@gmail.com",
		dateOfJoining: "2023-07-03",
		jobTitle: "Executive",
		businessUnit: "Silver Showroom",
		department: "PRO",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "rpsakthisree@gmail.com",
		dateOfJoining: "2023-07-22",
		jobTitle: "HR",
		businessUnit: "Gold Showroom",
		department: "HR",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "",
	},
	{
		email: "yogeshvaratharaj006@gmail.com",
		dateOfJoining: "2023-08-01",
		jobTitle: "Cashier",
		businessUnit: "Silver Showroom",
		department: "Cashier",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "gokil@vasavidinakaran.com",
		dateOfJoining: "2023-08-01",
		jobTitle: "Sales Executive",
		businessUnit: "Silver Showroom",
		department: "Golusu",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "saran@vasavi.com",
		dateOfJoining: "2023-08-07",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "rockstarabiram97@gmail.com",
		dateOfJoining: "2017-01-24",
		jobTitle: "Executive",
		businessUnit: "Gold Showroom",
		department: "Kids",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "shyam@vasavi.com",
		dateOfJoining: "2024-05-20",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "donaldreegan1809@gmail.com",
		dateOfJoining: "2024-05-02",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "",
		dateOfJoining: "2024-05-15",
		jobTitle: "Driver",
		businessUnit: "Gold Showroom",
		department: "Driver",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "PREMKUMAR",
	},
	{
		email: "vasuki9327@gmail.com",
		dateOfJoining: "2024-06-19",
		jobTitle: "Sales Executive",
		businessUnit: "Silver Showroom",
		department: "Silver Ornaments",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "selvamjeya494@gmail.com",
		dateOfJoining: "2024-06-19",
		jobTitle: "Sales Executive",
		businessUnit: "Gold Showroom",
		department: "Long Necklace",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "salominal@svtm.com",
		dateOfJoining: "2025-02-12",
		jobTitle: "Admin",
		businessUnit: "Gold Showroom",
		department: "Admin",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "PREMKUMAR",
	},
	{
		email: "muraliraja1327@gmail.com",
		dateOfJoining: "2025-02-12",
		jobTitle: "Executive",
		businessUnit: "Silver Showroom",
		department: "Telecalling",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "KARTHICK",
	},
	{
		email: "amothilal1981@gmail.com",
		dateOfJoining: "2025-02-17",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "harshithamanjunath771@gmail.com",
		dateOfJoining: "2025-02-12",
		jobTitle: "Executive",
		businessUnit: "Silver Showroom",
		department: "Telecalling",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "KARTHICK",
	},
	{
		email: "melavarasy861@gmail.com",
		dateOfJoining: "2025-02-12",
		jobTitle: "Sales Executive",
		businessUnit: "Silver Showroom",
		department: "SILVER JEWLLARY",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "bhagavathis099@gmail.com",
		dateOfJoining: "2025-02-12",
		jobTitle: "Accounts Executive",
		businessUnit: "Corp Office",
		department: "Accounts executive",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "EUGINE SAHAYARAJ.J",
	},
	{
		email: "jacksaran84@gmail.com",
		dateOfJoining: "2025-02-12",
		jobTitle: "Sales Executive",
		businessUnit: "Silver Showroom",
		department: "Sales Executive",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "dpknar52@gmail.com",
		dateOfJoining: "2025-02-12",
		jobTitle: "Receptionist",
		businessUnit: "Silver Showroom",
		department: "Receptionist",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "muthuraja25121998@gmail.com",
		dateOfJoining: "2024-07-16",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "nivimeenu@gmail.com",
		dateOfJoining: "2025-05-12",
		jobTitle: "Receptionist",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "",
		dateOfJoining: "2025-05-12",
		jobTitle: "Receptionist",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "dkmanobalaji@gmail.com",
		dateOfJoining: "2025-05-14",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "sarathssk1234@gmail.com",
		dateOfJoining: "2025-05-26",
		jobTitle: "Accounts Executive",
		businessUnit: "Corp Office",
		department: "Accounts",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "EUGINE SAHAYARAJ.J",
	},
	{
		email: "vinosenthil145@gmail.com",
		dateOfJoining: "2025-06-26",
		jobTitle: "Executive",
		businessUnit: "Corp Office",
		department: "GOLD - BARCODE",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "MURALI.K.M",
	},
	{
		email: "svtm515@gmail.com",
		dateOfJoining: "2025-06-26",
		jobTitle: "Executive",
		businessUnit: "Corp Office",
		department: "SILVER - BARCODE",
		location: "Sri Vasavi - Corporate Office",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "svtm517@gmail.com",
		dateOfJoining: "2025-06-26",
		jobTitle: "Executive",
		businessUnit: "Gold Showroom",
		department: "Appraiser",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "BALASUBRAMANIYAN.N",
	},
	{
		email: "svtm520@gmail.com",
		dateOfJoining: "2025-07-18",
		jobTitle: "Reception",
		businessUnit: "Silver Showroom",
		department: "Silver Reception",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "svtm521@gmail.com",
		dateOfJoining: "2025-07-18",
		jobTitle: "Reception",
		businessUnit: "Silver Showroom",
		department: "Silver Reception",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "svtm522@gmail.com",
		dateOfJoining: "2025-07-18",
		jobTitle: "Reception",
		businessUnit: "Silver Showroom",
		department: "Silver Reception",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "anushiya0164@gmail.com",
		dateOfJoining: "2025-09-01",
		jobTitle: "Reception",
		businessUnit: "Silver Showroom",
		department: "Reception",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "svtm526@gmail.cocm",
		dateOfJoining: "2025-09-01",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "SATHISH KUMAR.M",
	},
	{
		email: "kalaimithru@gmail.com",
		dateOfJoining: "2025-09-03",
		jobTitle: "Reception",
		businessUnit: "Silver Showroom",
		department: "Reception",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "S SURESH",
	},
	{
		email: "sankarajith052@gmail.com",
		dateOfJoining: "2025-09-11",
		jobTitle: "Reception",
		businessUnit: "Gold Showroom",
		department: "Reception",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "R.SENTHILBABU",
	},
	{
		email: "lakshmi@gmail.com",
		dateOfJoining: "2020-06-01",
		jobTitle: "House Keeping",
		businessUnit: "Gold Showroom",
		department: "House Keeping",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "",
	},
	{
		email: "panja@vasavi.com",
		dateOfJoining: "2015-05-10",
		jobTitle: "House Keeping",
		businessUnit: "Silver Showroom",
		department: "House Keeping",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "",
	},
	{
		email: "balakannan.g.1958@gmail.com",
		dateOfJoining: "2004-01-01",
		jobTitle: "Supervisor",
		businessUnit: "Silver Showroom",
		department: "Supervisor",
		location: "Sri Vasavi - House of Silver",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "",
	},
	{
		email: "murug@vasavi.com",
		dateOfJoining: "2007-03-01",
		jobTitle: "Electrical",
		businessUnit: "Gold Showroom",
		department: "EDP",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "",
	},
	{
		email: "sarav@vasavit.com",
		dateOfJoining: "2008-01-01",
		jobTitle: "SECURITY",
		businessUnit: "Gold Showroom",
		department: "SECURITY",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "",
	},
	{
		email: "marut@vasavi.com",
		dateOfJoining: "1993-01-01",
		jobTitle: "Driver",
		businessUnit: "Gold Showroom",
		department: "Driver",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "",
	},
	{
		email: "jegat@vasavi.com",
		dateOfJoining: "2014-02-01",
		jobTitle: "Driver",
		businessUnit: "Gold Showroom",
		department: "Driver",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "",
	},
	{
		email: "anand@vasavi.com",
		dateOfJoining: "2019-01-01",
		jobTitle: "Driver",
		businessUnit: "Gold Showroom",
		department: "Driver",
		location: "Sri Vasavi Thanga Maaligai",
		legalEntity: "SRI VASAVI THANGA MAALIGAI",
		reportingTo: "",
	},
];

// Helper to parse date strings in DD-Mmm-YY format
function parseDate(dateStr: string): string {
	if (!dateStr || dateStr.trim() === "")
		return new Date().toISOString().split("T")[0];

	try {
		// Format: DD-Mmm-YY
		const parts = dateStr.split("-");
		if (parts.length !== 3) return new Date().toISOString().split("T")[0];

		const day = parts[0];
		const monthStr = parts[1];
		const yearStr = parts[2];

		const months: { [key: string]: number } = {
			Jan: 1,
			Feb: 2,
			Mar: 3,
			Apr: 4,
			May: 5,
			Jun: 6,
			Jul: 7,
			Aug: 8,
			Sep: 9,
			Oct: 10,
			Nov: 11,
			Dec: 12,
		};

		const month = months[monthStr];
		if (!month) return new Date().toISOString().split("T")[0];

		const year = Number.parseInt(yearStr);
		const fullYear = year > 50 ? 1900 + year : 2000 + year;

		const date = new Date(fullYear, month - 1, Number.parseInt(day));
		return date.toISOString().split("T")[0];
	} catch {
		return new Date().toISOString().split("T")[0];
	}
}

async function seedEmployees() {
	try {
		console.log("🌱 Starting to seed employee data...\n");

		// Fetch all reference data
		console.log("📋 Loading reference data...");

		const jobTitles = await db.select().from(jobTitle);
		const businessUnits = await db.select().from(businessUnit);
		const departments = await db.select().from(department);
		const locations = await db.select().from(location);
		const legalEntities = await db.select().from(legalEntity);
		const users = await db.select().from(user);

		console.log(`  ✅ Job Titles: ${jobTitles.length}`);
		console.log(`  ✅ Business Units: ${businessUnits.length}`);
		console.log(`  ✅ Departments: ${departments.length}`);
		console.log(`  ✅ Locations: ${locations.length}`);
		console.log(`  ✅ Legal Entities: ${legalEntities.length}`);
		console.log(`  ✅ Users: ${users.length}\n`);

		// Create lookup maps
		const jobTitleMap = new Map(jobTitles.map((jt) => [jt.name, jt.id]));
		const businessUnitMap = new Map(
			businessUnits.map((bu) => [bu.name, bu.id]),
		);
		const departmentMap = new Map(departments.map((d) => [d.name, d.id]));
		const locationMap = new Map(locations.map((l) => [l.name, l.id]));
		const legalEntityMap = new Map(legalEntities.map((le) => [le.name, le.id]));
		const userEmailMap = new Map(users.map((u) => [u.email, u.id]));
		const userNameMap = new Map(
			users.map((u) => {
				// Extract first part of name for matching with reporting to
				const nameParts = u.name.split(" ");
				return [nameParts[0], u.id];
			}),
		);

		console.log("🔄 Processing employees...\n");

		let successCount = 0;
		let skipCount = 0;
		const failedEmployees: string[] = [];

		for (const emp of employeeData) {
			try {
				// Skip if no email and cannot identify user
				if (!emp.email || emp.email.trim() === "") {
					console.log("⚠️  Skipping employee with no email");
					skipCount++;
					continue;
				}

				// Get user ID
				const userId = userEmailMap.get(emp.email.toLowerCase());
				if (!userId) {
					console.log(
						`⚠️  User not found for email: ${emp.email} (Skipping - user must exist first)`,
					);
					skipCount++;
					continue;
				}

				// Check if employee record already exists
				const existingEmployee = await db
					.select()
					.from(employee)
					.where(eq(employee.userId, userId));

				if (existingEmployee.length > 0) {
					console.log(`⚠️  Employee record already exists for: ${emp.email}`);
					skipCount++;
					continue;
				}

				// Get reference IDs
				const jobTitleId = jobTitleMap.get(emp.jobTitle);
				const businessUnitId = businessUnitMap.get(emp.businessUnit);
				const departmentId = departmentMap.get(emp.department);
				const locationId = locationMap.get(emp.location);
				const legalEntityId = legalEntityMap.get(emp.legalEntity);

				if (!jobTitleId) {
					console.log(`❌ Job Title not found: ${emp.jobTitle}`);
					failedEmployees.push(emp.email);
					continue;
				}
				if (!businessUnitId) {
					console.log(`❌ Business Unit not found: ${emp.businessUnit}`);
					failedEmployees.push(emp.email);
					continue;
				}
				if (!departmentId) {
					console.log(`❌ Department not found: ${emp.department}`);
					failedEmployees.push(emp.email);
					continue;
				}
				if (!locationId) {
					console.log(`❌ Location not found: ${emp.location}`);
					failedEmployees.push(emp.email);
					continue;
				}
				if (!legalEntityId) {
					console.log(`❌ Legal Entity not found: ${emp.legalEntity}`);
					failedEmployees.push(emp.email);
					continue;
				}

				// Get reporting to user ID if available
				let reportingToUserId = null;
				if (emp.reportingTo && emp.reportingTo.trim() !== "") {
					// Try to find by full name or first name
					let foundUserId = null;

					// First try exact name match
					for (const u of users) {
						if (u.name.includes(emp.reportingTo)) {
							foundUserId = u.id;
							break;
						}
					}

					// If not found, try first part of reporting to name
					if (!foundUserId) {
						const reportingFirstName = emp.reportingTo.split(".")[0];
						foundUserId = userNameMap.get(reportingFirstName);
					}

					reportingToUserId = foundUserId;
				}

				// Create employee record
				await db.insert(employee).values({
					id: uuidv4(),
					userId,
					dateOfJoining: parseDate(emp.dateOfJoining),
					jobTitleId,
					businessUnitId,
					departmentId,
					locationId,
					legalEntityId,
					reportingToUserId,
				});

				console.log(`✅ Created employee record for: ${emp.email}`);
				successCount++;
			} catch (error) {
				const errorMsg = error instanceof Error ? error.message : String(error);
				console.error(`❌ Failed for ${emp.email}:`, errorMsg);
				failedEmployees.push(emp.email);
			}
		}

		console.log("\n" + "=".repeat(50));
		console.log("📊 Seed Summary:");
		console.log(`✅ Successfully created: ${successCount} employee records`);
		console.log(`⚠️  Skipped: ${skipCount} employees`);
		console.log(`❌ Failed: ${failedEmployees.length} employees`);

		if (failedEmployees.length > 0) {
			console.log("\n❌ Failed employees:");
			failedEmployees.forEach((email) => {
				console.log(`  - ${email}`);
			});
		}

		console.log("=".repeat(50));
		console.log("✨ Employee seeding completed!");
	} catch (error) {
		console.error("❌ Seed failed:", error);
		process.exit(1);
	}
}

seedEmployees();
